import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.KotlinJvm
import com.vanniktech.maven.publish.SourcesJar
import java.io.File

// ==========================================
// Test/dev-only desktop JVM artifact.
//
// Published as com.rouast:vitallens-core-jvm — deliberately NOT the same
// coordinate as the Android AAR (com.rouast:vitallens-core, see
// ../android/build.gradle.kts). It bundles host cdylibs (macOS + Linux, see
// nativeLibs/) laid out for JNA's desktop resource-extraction loader, so
// that plain JVM `./gradlew test` runs in consumers (e.g. vitallens-android)
// can exercise real Rust-backed UniFFI objects via
// `testImplementation("com.rouast:vitallens-core-jvm:...")`, without a local
// Rust toolchain. This must never be added as a production `implementation`
// dependency of a shipped Android app.
// ==========================================

// ==========================================
// Version (single source of truth: ../../Cargo.toml)
// ==========================================
// NOTE: `rootDir` is always the settings.gradle.kts directory (kotlin/), the
// same for every subproject — not this module's own directory — so this is
// the identical expression used in ../android/build.gradle.kts.

val cargoVersion: String = File(rootDir, "../Cargo.toml").readLines()
    .firstOrNull { it.trim().startsWith("version =") }
    ?.substringAfter("\"")
    ?.substringBefore("\"")
    ?: error("Could not determine version from ../Cargo.toml")

// ==========================================
// Plugins
// ==========================================

plugins {
    // Versions declared once in the aggregator root (../build.gradle.kts,
    // `apply false`) and applied here unversioned — see the comment there
    // for why (shared multi-project plugin classpath).
    id("org.jetbrains.kotlin.jvm")
    id("com.vanniktech.maven.publish")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    // Deliberately NOT jvmToolchain(17): that requests actual toolchain
    // resolution (a JDK 17 installation, or auto-provisioning, which isn't
    // configured), whereas source/targetCompatibility above just picks the
    // -source/-target javac flags on whatever JDK runs Gradle. Pinning
    // compileKotlin's target the same way keeps it consistent with
    // compileJava without requiring a JDK 17 install — matches the Android
    // module's approach (../android/build.gradle.kts).
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }

    sourceSets {
        main {
            // Generated by `make build-jvm` (uniffi-bindgen --language kotlin).
            // Same generated sources as the Android AAR (../android/build.gradle.kts)
            // — UniFFI bindings don't change per native target.
            kotlin.srcDir("../../bindings/kotlin")
            // JNA desktop resource layout: nativeLibs/<os-arch>/libvitallens_core.<ext>.
            // `make build-jvm` (local, macOS dev machine) only populates the
            // darwin-aarch64/darwin-x86-64 slices. The published artifact also
            // carries linux-x86-64, assembled in CI by merging per-OS native
            // build artifacts (see .github/workflows/release.yml's jvm-release
            // job) — a Linux .so can't be produced from this machine directly.
            resources.srcDir("nativeLibs")
        }
    }
}

dependencies {
    // The DESKTOP JNA jar (bundled with its own dispatch natives for
    // darwin/linux/win32) — NOT the `@aar` variant the Android module uses
    // (../android/build.gradle.kts), which is an Android-only stripped
    // artifact with no desktop dispatch library. `api` so it's recorded in
    // the POM and reaches test consumers transitively, matching the Android
    // module's reasoning for using `api` there.
    api("net.java.dev.jna:jna:5.12.0")
}

// ==========================================
// Publishing (Maven Central via the Central Portal)
// ==========================================

mavenPublishing {
    configure(
        KotlinJvm(
            JavadocJar.Empty(),
            SourcesJar.Sources(),
        )
    )
    publishToMavenCentral()

    // Only sign when credentials are actually present — see
    // ../android/build.gradle.kts for the full rationale (identical here).
    if (project.hasProperty("signingInMemoryKey")) {
        signAllPublications()
    }

    // Deliberately a distinct artifactId from the Android AAR
    // (com.rouast:vitallens-core) so this test/dev-only desktop jar can never
    // be pulled in as a production Android dependency by coordinate alone.
    coordinates("com.rouast", "vitallens-core-jvm", cargoVersion)

    pom {
        name.set("VitalLens Core (JVM)")
        description.set(
            "Desktop JVM native library for VitalLens Core, for local " +
                "Kotlin/JVM unit testing of real Rust-backed UniFFI objects. " +
                "Test/dev-only — not part of the production Android SDK."
        )
        url.set("https://github.com/Rouast-Labs/vitallens-core")

        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/licenses/MIT")
            }
        }

        developers {
            developer {
                id.set("rouast-labs")
                name.set("Rouast Labs")
                url.set("https://github.com/Rouast-Labs")
            }
        }

        scm {
            url.set("https://github.com/Rouast-Labs/vitallens-core")
            connection.set("scm:git:git://github.com/Rouast-Labs/vitallens-core.git")
            developerConnection.set("scm:git:ssh://git@github.com/Rouast-Labs/vitallens-core.git")
        }
    }
}
