import java.io.File

// ==========================================
// Version (single source of truth: ../Cargo.toml)
// ==========================================

val cargoVersion: String = File(rootDir, "../Cargo.toml").readLines()
    .firstOrNull { it.trim().startsWith("version =") }
    ?.substringAfter("\"")
    ?.substringBefore("\"")
    ?: error("Could not determine version from ../Cargo.toml")

// ==========================================
// Plugins
// ==========================================

// Relies on AGP's built-in Kotlin support to compile the UniFFI-generated
// Kotlin bindings — do NOT apply org.jetbrains.kotlin.android/jvm alongside
// com.android.library; as of AGP 9 that combination is a hard build error.
plugins {
    id("com.android.library") version "9.1.1"
    id("maven-publish")
}

android {
    namespace = "com.rouast.vitallens.core"
    compileSdk = 36

    defaultConfig {
        minSdk = 21
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        getByName("main") {
            // Generated by `make build-android` (uniffi-bindgen --language kotlin).
            kotlin.srcDir("../bindings/kotlin")
            // Populated by `make build-android` (cargo ndk -o android/jniLibs ...).
            jniLibs.srcDir("jniLibs")
        }
    }

    // Required since AGP 7.1+ for the `release` software component to exist —
    // without this, `components["release"]` below resolves to nothing and
    // maven-publish silently produces an empty artifact.
    publishing {
        singleVariant("release")
    }
}

dependencies {
    // UniFFI 0.28's generated Kotlin bindings call into JNA (com.sun.jna.*).
    // Version pinned to UniFFI's own documented minimum ("JNA 5.12.0 or
    // greater is required") rather than the latest, to keep this new
    // transitive dependency's AAR metadata floor (minCompileSdk /
    // minAndroidGradlePluginVersion) as low as possible for downstream
    // consumers — see `make dist-android` verification notes. `api` (not
    // `implementation`) so maven-publish records it in the POM and it
    // reaches consumers transitively.
    api("net.java.dev.jna:jna:5.12.0@aar")
}

publishing {
    publications {
        register<MavenPublication>("release") {
            groupId = "com.rouast"
            artifactId = "vitallens-core-android"
            version = cargoVersion

            afterEvaluate {
                from(components["release"])
            }
        }
    }
}
