import com.vanniktech.maven.publish.AndroidSingleVariantLibrary
import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.SourcesJar
import java.io.File

// ==========================================
// Version (single source of truth: ../../Cargo.toml)
// ==========================================
// NOTE: `rootDir` is always the settings.gradle.kts directory (kotlin/), the
// same for every subproject — not this module's own directory.

val cargoVersion: String = File(rootDir, "../Cargo.toml").readLines()
    .firstOrNull { it.trim().startsWith("version =") }
    ?.substringAfter("\"")
    ?.substringBefore("\"")
    ?: error("Could not determine version from ../Cargo.toml")

// ==========================================
// Plugins
// ==========================================

// Relies on AGP's built-in Kotlin support to compile the UniFFI-generated
// Kotlin bindings — do NOT apply org.jetbrains.kotlin.android/jvm alongside
// com.android.library; as of AGP 9 that combination is a hard build error.
//
// com.vanniktech.maven.publish applies/manages `maven-publish` internally —
// do not additionally apply `id("maven-publish")` alongside it.
//
// Versions are declared once in the aggregator root (../build.gradle.kts,
// `apply false`) and applied here unversioned — see the comment there for
// why (shared multi-project plugin classpath).
plugins {
    id("com.android.library")
    id("com.vanniktech.maven.publish")
}

android {
    namespace = "com.rouast.vitallens.core"
    compileSdk = 36

    defaultConfig {
        minSdk = 21
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        getByName("main") {
            // Generated by `make build-android` (uniffi-bindgen --language kotlin).
            kotlin.srcDir("../../bindings/kotlin")
            // Populated by `make build-android` (cargo ndk -o kotlin/android/jniLibs ...).
            jniLibs.srcDir("jniLibs")
        }
    }

    // NOTE: no `publishing { singleVariant("release") }` here — the
    // `AndroidSingleVariantLibrary("release", ...)` config in mavenPublishing{}
    // below declares that itself. Declaring it in both places is a hard
    // Gradle error ("...not allowed").
}

dependencies {
    // UniFFI 0.28's generated Kotlin bindings call into JNA (com.sun.jna.*).
    // Version pinned to UniFFI's own documented minimum ("JNA 5.12.0 or
    // greater is required") rather than the latest, to keep this new
    // transitive dependency's AAR metadata floor (minCompileSdk /
    // minAndroidGradlePluginVersion) as low as possible for downstream
    // consumers — see `make dist-android` verification notes. `api` (not
    // `implementation`) so maven-publish records it in the POM and it
    // reaches consumers transitively.
    api("net.java.dev.jna:jna:5.12.0@aar")
}

// ==========================================
// Publishing (Maven Central via the Central Portal)
// ==========================================

mavenPublishing {
    configure(
        AndroidSingleVariantLibrary(
            JavadocJar.Empty(),
            SourcesJar.Sources(),
            "release",
        )
    )
    publishToMavenCentral()

    // Only sign when credentials are actually present (in CI, via the
    // maven-central GitHub Environment's GPG_PRIVATE_KEY/GPG_PASSPHRASE
    // secrets, exposed as ORG_GRADLE_PROJECT_signingInMemoryKey* env vars).
    // signAllPublications() unconditionally requires a signatory, which
    // would otherwise break `make dist-android` -> publishToMavenLocal on a
    // dev machine that correctly has no GPG key. Gradle auto-exposes any
    // ORG_GRADLE_PROJECT_x env var as project property `x`, so this single
    // check covers both the CI (env var) and local (gradle.properties) cases.
    if (project.hasProperty("signingInMemoryKey")) {
        signAllPublications()
    }

    // Coordinate matches the existing PyPI ("vitallens-core") and npm
    // ("vitallens-core") package names exactly. The artifactId is a literal
    // string here — deliberately not derived from project.name (which is
    // just "android", the Gradle module folder name) — so a folder rename
    // can never silently change the published coordinate.
    coordinates("com.rouast", "vitallens-core", cargoVersion)

    pom {
        name.set("VitalLens Core")
        description.set("The universal Rust engine powering the VitalLens ecosystem.")
        url.set("https://github.com/Rouast-Labs/vitallens-core")

        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/licenses/MIT")
            }
        }

        developers {
            developer {
                id.set("rouast-labs")
                name.set("Rouast Labs")
                url.set("https://github.com/Rouast-Labs")
            }
        }

        scm {
            url.set("https://github.com/Rouast-Labs/vitallens-core")
            connection.set("scm:git:git://github.com/Rouast-Labs/vitallens-core.git")
            developerConnection.set("scm:git:ssh://git@github.com/Rouast-Labs/vitallens-core.git")
        }
    }
}
